# Generated by Django 2.0.4 on 2018-11-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enderecos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linha1', models.TextField(max_length=250)),
                ('linha2', models.TextField(blank=True, max_length=250, null=True)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=100)),
                ('latitude', models.IntegerField(blank=True, null=True)),
                ('longitude', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
